name: Deploy Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: blocksone
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/blocksone/devops-project
            git pull origin main
            
            docker stop my-container || true
            docker rm my-container || true
            
            docker build -t devops-app .
            docker run -d -p 3000:3000 --name my-container devops-app
